// alarmliste.js - Contains all alarm types for the emergency response simulation

const alarmTypes = [
    "Bygningsbrand (Villa/Rækkehus)", "Skovbrand", "Affaldsbrand", "Industri- og fabriksbrand", "Brand i erhvervsbygning",
    "Fritstående bygning – brand", "Brand i kælder", "Bilbrand", "Brand i container", "Brand i maskinhus", "Elbrand", 
    "Brand i affaldscontainer", "Brand på tag", "Brand i skur", "Hedebrand", "Brand i stald", "Brand i landbrugsbygning", 
    "Brand i campingvogn", "Brand i båd", "Brand på vej", "Gaseksplosion", "Brand i traktor", "Brand i tog", 
    "Eksplosion i industri", "Brand på fabrik", "Brand på containerterminal", "Brand i motorcykel", "Menneskelig fejl ved brand", 
    "Brand i silo", "Brand på parkeringsplads", "Brand i tømmerlager", "Brand i offentligt toilet", "Brand i lejlighed", 
    "Brand i restaurant", "Brand på byggeplads", "Brand i højhus", "Brand på lufthavn", "Brand på skib", "Brand i gasværk", 
    "Brand i græsmark", "Brand i industribygning", "Brand i fjernvarme", "Brand i teknikrum", "Brand på station", 
    "Brand på rasteplads", "Brand i højhus", "Brand i stuehus", "Brand i lastbil", "Brand i maskinerum", "Brand på motorvej", 
    "Brand i telefonkiosk", "Brand i containerpark", "Brud på gasledning", "Brand i skovrydning", "Brand i trafikskilt", 
    "Brand i havn", "Brand i betongulv", "Brand på helikopter", "Brand i samlingshus", "Brand i daginstitution", 
    "Brand på rasteplads", "Brand i skolebygning", "Brand i el-tavle", "Brand på sportshal", "Brand i kulturhus", 
    "Brand i brokonstruktion", "Brand i brohus", "Brand i transformerstation", "Brand i stengrå område", "Brand i lysmast", 
    "Brand i bunker", "Brand i butikslager", "Brand i underjordisk garage", "Brand på autobahn", "Brand på affaldsplads", 
    "Brand på loft", "Brand i bunker", "Brand på tankstation", "Brand på arbejdsplads", "Brand i bygning med kemikalier", 
    "Brand på fritidshusområde", "Brand i skovområde", "Brand i industrikøkken", "Brand i brandstation", "Brand i jernbaneoverskæring", 
    "Brand i værksted", "Brand i bygningskonstruktion", "Brand i vejledningstelt", "Brand i industripark", "Brand på metrostation", 
    "Brand på lufthavnsområde", "Brand i kraftværk", "Brand i affaldsdepot", "Brand i cykelskure", "Brand i containerby", 
    "Brand på flisearbejde", "Brand i maritimt område", "Brand i psykiatrisk afdeling", "Brand i dyrepark", "Brand i kemisk lager",
    "Hjemmepleje: Aktiveret nødkald uden respons",
    "Hjemmepleje: Borger faldet på badeværelse",
    "Hjemmepleje: Borger ikke mødt til planlagt besøg",
    "Hjemmepleje: Hjælp til medicinindtag",
    "Hjemmepleje: Forvirret borger åbner ikke døren",
    "Hjemmepleje: Borger låst inde",
    "Hjemmepleje: Mistanke om dehydrering",
    "Hjemmepleje: Mistanke om lavt blodsukker",
    "Hjemmepleje: Akut angst",
    "Hjemmepleje: Stærke smerter i ben",
    "Hjemmepleje: Akut forværring i vejrtrækning",
    "Hjemmepleje: Mistanke om urinvejsinfektion",
    "Hjemmepleje: Borger med svær diarré",
    "Hjemmepleje: Manglende kontakt til borger",
    "Hjemmepleje: Feber hos svækket borger",
    "Hjemmepleje: Alvorlig kløe og udslæt",
    "Hjemmepleje: Manglende varme i hjemmet",
    "Hjemmepleje: Mistanke om forstuvet ankel",
    "Hjemmepleje: Pludselig svimmelhed",
    "Hjemmepleje: Mistanke om forvirring/demens",
    "Hjemmepleje: Psykisk ustabil borger",
    "Hjemmepleje: Borger nægter behandling",
    "Hjemmepleje: Mistanke om depression",
    "Hjemmepleje: Borger græder og ryster",
    "Hjemmepleje: Fald udendørs ved indgang",
    "Hjemmepleje: Akut tandpine",
    "Hjemmepleje: Uventet besvimelse",
    "Hjemmepleje: Borger er aggressiv",
    "Hjemmepleje: Mistanke om brækket hofte",
    "Hjemmepleje: Mistet bevidsthed under bad",
    "Hjemmepleje: Borger uden strøm og varme",
    "Hjemmepleje: Vand på gulvet i køkken",
    "Hjemmepleje: Opkast i længere tid",
    "Hjemmepleje: Mistet balance på trapper",
    "Hjemmepleje: Mistanke om allergisk reaktion",
    "Hjemmepleje: Borger bløder fra sår",
    "Hjemmepleje: Tvivl om korrekt medicinindtag",
    "Hjemmepleje: Mistanke om væskemangel",
    "Hjemmepleje: Mistanke om infektion",
    "Hjemmepleje: Borger kan ikke rejse sig",
    "Hjemmepleje: Borger savner pårørende",
    "Hjemmepleje: Ingen kontakt ved døren",
    "Hjemmepleje: Mistanke om madforgiftning",
    "Hjemmepleje: Nedsat bevidsthedsniveau",
    "Hjemmepleje: Borger har slået hovedet",
    "Hjemmepleje: Behov for akut mobilisering",
    "Hjemmepleje: Forhøjet temperatur",
    "Hjemmepleje: Røg lugt i lejlighed",
    "Hjemmepleje: Akut psykisk krise",
    "Hjemmepleje: Borger nægter adgang",
    "Hjemmepleje: Nedsat funktionsniveau"
];
