// alarmliste.js - Contains all alarm types for the emergency response simulation

const alarmTypes = [
       "Bygningsbrand (Villa/Rækkehus)", "Skovbrand", "Affaldsbrand", "Industri- og fabriksbrand", "Brand i erhvervsbygning",
    "Fritstående bygning – brand", "Brand i kælder", "Bilbrand", "Brand i container", "Brand i maskinhus", "Elbrand", 
    "Brand i affaldscontainer", "Brand på tag", "Brand i skur", "Hedebrand", "Brand i stald", "Brand i landbrugsbygning", 
    "Brand i campingvogn", "Brand i båd", "Brand på vej", "Gaseksplosion", "Brand i traktor", "Brand i tog", 
    "Eksplosion i industri", "Brand på fabrik", "Brand på containerterminal", "Brand i motorcykel", "Menneskelig fejl ved brand", 
    "Brand i silo", "Brand på parkeringsplads", "Brand i tømmerlager", "Brand i offentligt toilet", "Brand i lejlighed", 
    "Brand i restaurant", "Brand på byggeplads", "Brand i højhus", "Brand på lufthavn", "Brand på skib", "Brand i gasværk", 
    "Brand i græsmark", "Brand i industribygning", "Brand i fjernvarme", "Brand i teknikrum", "Brand på station", 
    "Brand på rasteplads", "Brand i højhus", "Brand i stuehus", "Brand i lastbil", "Brand i maskinerum", "Brand på motorvej", 
    "Brand i telefonkiosk", "Brand i containerpark", "Brud på gasledning", "Brand i skovrydning", "Brand i trafikskilt", 
    "Brand i havn", "Brand i betongulv", "Brand på helikopter", "Brand i samlingshus", "Brand i daginstitution", 
    "Brand på rasteplads", "Brand i skolebygning", "Brand i el-tavle", "Brand på sportshal", "Brand i kulturhus", 
    "Brand i brokonstruktion", "Brand i brohus", "Brand i transformerstation", "Brand i stengrå område", "Brand i lysmast", 
    "Brand i bunker", "Brand i butikslager", "Brand i underjordisk garage", "Brand på autobahn", "Brand på affaldsplads", 
    "Brand på loft", "Brand i bunker", "Brand på tankstation", "Brand på arbejdsplads", "Brand i bygning med kemikalier", 
    "Brand på fritidshusområde", "Brand i skovområde", "Brand i industrikøkken", "Brand i brandstation", "Brand i jernbaneoverskæring", 
    "Brand i værksted", "Brand i bygningskonstruktion", "Brand i vejledningstelt", "Brand i industripark", "Brand på metrostation", 
    "Brand på lufthavnsområde", "Brand i kraftværk", "Brand i affaldsdepot", "Brand i cykelskure", "Brand i containerby", 
    "Brand på flisearbejde", "Brand i maritimt område", "Brand i psykiatrisk afdeling", "Brand i dyrepark", "Brand i kemisk lager",
    "Hjemmepleje: Aktiveret nødkald uden respons",
    "Hjemmepleje: Borger faldet på badeværelse",
    "Hjemmepleje: Borger ikke mødt til planlagt besøg",
    "Hjemmepleje: Hjælp til medicinindtag",
    "Hjemmepleje: Forvirret borger åbner ikke døren",
    "Hjemmepleje: Borger låst inde",
    "Hjemmepleje: Mistanke om dehydrering",
    "Hjemmepleje: Mistanke om lavt blodsukker",
    "Hjemmepleje: Akut angst",
    "Hjemmepleje: Stærke smerter i ben",
    "Hjemmepleje: Akut forværring i vejrtrækning",
    "Hjemmepleje: Mistanke om urinvejsinfektion",
    "Hjemmepleje: Borger med svær diarré",
    "Hjemmepleje: Manglende kontakt til borger",
    "Hjemmepleje: Feber hos svækket borger",
    "Hjemmepleje: Alvorlig kløe og udslæt",
    "Hjemmepleje: Manglende varme i hjemmet",
    "Hjemmepleje: Mistanke om forstuvet ankel",
    "Hjemmepleje: Pludselig svimmelhed",
    "Hjemmepleje: Mistanke om forvirring/demens",
    "Hjemmepleje: Psykisk ustabil borger",
    "Hjemmepleje: Borger nægter behandling",
    "Hjemmepleje: Mistanke om depression",
    "Hjemmepleje: Borger græder og ryster",
    "Hjemmepleje: Fald udendørs ved indgang",
    "Hjemmepleje: Akut tandpine",
    "Hjemmepleje: Uventet besvimelse",
    "Hjemmepleje: Borger er aggressiv",
    "Hjemmepleje: Mistanke om brækket hofte",
    "Hjemmepleje: Mistet bevidsthed under bad",
    "Hjemmepleje: Borger uden strøm og varme",
    "Hjemmepleje: Vand på gulvet i køkken",
    "Hjemmepleje: Opkast i længere tid",
    "Hjemmepleje: Mistet balance på trapper",
    "Hjemmepleje: Mistanke om allergisk reaktion",
    "Hjemmepleje: Borger bløder fra sår",
    "Hjemmepleje: Tvivl om korrekt medicinindtag",
    "Hjemmepleje: Mistanke om væskemangel",
    "Hjemmepleje: Mistanke om infektion",
    "Hjemmepleje: Borger kan ikke rejse sig",
    "Hjemmepleje: Borger savner pårørende",
    "Hjemmepleje: Ingen kontakt ved døren",
    "Hjemmepleje: Mistanke om madforgiftning",
    "Hjemmepleje: Nedsat bevidsthedsniveau",
    "Hjemmepleje: Borger har slået hovedet",
    "Hjemmepleje: Behov for akut mobilisering",
    "Hjemmepleje: Forhøjet temperatur",
    "Hjemmepleje: Røg lugt i lejlighed",
    "Hjemmepleje: Akut psykisk krise",
    "Hjemmepleje: Borger nægter adgang",
    "Hjemmepleje: Nedsat funktionsniveau",
    // Politi opgaver
    "Politi: Indbrud i villa",
    "Politi: Butikstyveri i supermarked",
    "Politi: Færdselsuheld med personskade",
    "Politi: Vold og trusler på offentlig sted",
    "Politi: Hærværk på skole",
    "Politi: Narkotikahandel på gadeplan",
    "Politi: Røveri mod pengeinstitut",
    "Politi: Familievold i lejlighed",
    "Politi: Biltyv i gang",
    "Politi: Støjgener fra fest",
    "Politi: Mistænkelig person ved børnehave",
    "Politi: Cykeltyv på stationen",
    "Politi: Spirituskørsel kontrol",
    "Politi: Knivstikkeri i byens centrum",
    "Politi: Brandstiftelse mistanke",
    "Politi: Demonstration uden tilladelse",
    "Politi: Hjemmerøveri i parcelhus",
    "Politi: Bedragerisk telefonopkald",
    "Politi: Voldelig person på restaurant",
    "Politi: Taskerøveri ved bankautomat",
    "Politi: Illegal graffiti på bygning",
    "Politi: Hashklub razzia",
    "Politi: Trafikuheld på motorvej",
    "Politi: Stalking anmeldelse",
    "Politi: Husspektakel med trusler",
    "Politi: Våben besiddelse ulovligt",
    "Politi: Dokumentfalsk",
    "Politi: Menneskesmugling",
    "Politi: Bankrøveri i gang",
    "Politi: Kidnapning anmeldt",
    "Politi: Terrorisme mistanke",
    "Politi: Drab anmeldt",
    "Politi: Voldtægt anmeldt",
    "Politi: Organiseret kriminalitet",
    "Politi: Cyberkriminalitet",
    "Politi: Hvidvaskning af penge",
    "Politi: Smugling af narkotika",
    "Politi: Prostitution ulovlig",
    "Politi: Pengeafpresning",
    "Politi: Identitetstyveri",
    "Politi: Kreditkortsvindel",
    "Politi: Vandalism på offentlig ejendom",
    "Politi: Ulovlig våbenhandel",
    "Politi: Menneskehandel mistanke",
    "Politi: Korruption anklage",
    "Politi: Trussel mod offentlig person",
    "Politi: Falsk alarm til nødetaterne",
    "Politi: Ulovlig demonstration",
    "Politi: Chikane på arbejdspladsen",
    "Politi: Økonomisk svindel",
    "Politi: Miljøkriminalitet",
    "Politi: Dyremishandling anmeldt",
    "Politi: Computerhacking",
    "Politi: Afpresning via internet",
    "Politi: Ungdomskriminalitet",
    "Politi: Beruselse i trafikken",
    "Politi: Skyderi i byen",
    "Politi: Gidseltagning",
    "Politi: Bombetrussel",
    "Politi: Ulovlig hasardspil",
    "Politi: Smugling over grænsen",
    "Politi: Skatteunddragelse",
    "Politi: Falsk anklage",
    "Politi: Tyveri af køretøj",
    "Politi: Medicinskandal",
    "Politi: Ulovlig overvågning",
    "Politi: Racisme hændelse",
    "Politi: Kontrol af farlig person",
    "Politi: Mistænkelig dødsårsag",
    "Politi: Ulovligt byggeri",
    "Politi: Internet svindel",
    "Politi: Trusler mod skole",
    // Ambulance opgaver
    "Ambulance: Hjertestop i offentligt rum",
    "Ambulance: Trafikuheld med tilskadekomne",
    "Ambulance: Fald fra stige",
    "Ambulance: Fødselshjælp i hjemmet",
    "Ambulance: Forgiftning ved kemikalier",
    "Ambulance: Allergisk chok",
    "Ambulance: Slagtilfælde hos ældre",
    "Ambulance: Knoglebrud efter cykelulykke",
    "Ambulance: Brandsår fra ulykke",
    "Ambulance: Overdosis narkotika",
    "Ambulance: Psykisk krise med selvmordstanker",
    "Ambulance: Diabetisk chok",
    "Ambulance: Kvælningsulykke",
    "Ambulance: Epileptisk anfald",
    "Ambulance: Astmaanfald hos barn",
    "Ambulance: Arbejdsulykke på byggeplads",
    "Ambulance: Alvorlig blødning",
    "Ambulance: Hjernerystelse efter fald",
    "Ambulance: Mavesmerter hos gravid",
    "Ambulance: Bevidstløs person i park",
    "Ambulance: Drukneulykke ved strand",
    "Ambulance: El-ulykke i hjemmet",
    "Ambulance: Sportsulykke på stadion",
    "Ambulance: Fødevareforgigtning",
    "Ambulance: Akut vejrtrækningsbesvær",
    "Ambulance: Kramper hos barn",
    "Ambulance: Alvorlig hovedpine",
    "Ambulance: Brystsmerter hos ældre",
    "Ambulance: Dehydrering i varme",
    "Ambulance: Insektstik allergisk reaktion",
    "Ambulance: Voldelig patient transport",
    "Ambulance: Psykiatrisk patient transport",
    "Ambulance: Præmatur fødsel",
    "Ambulance: Blodpropmisdannelse",
    "Ambulance: Akut mavepine",
    "Ambulance: Hypothermi efter kulde",
    "Ambulance: Forgiftning med medicin",
    "Ambulance: Falsk hjertestop",
    "Ambulance: Alkoholforgiftning",
    "Ambulance: Hyperventilation",
    "Ambulance: Besvimelse i offentlighed",
    "Ambulance: Rygskade efter løft",
    "Ambulance: Sår der bløder kraftigt",
    "Ambulance: Koma patient",
    "Ambulance: Feber hos spædbarn",
    "Ambulance: Mistanke om hjerneskade",
    "Ambulance: Akut nyreproblemer",
    "Ambulance: Leverproblemer akut",
    "Ambulance: Blodsukker for højt",
    "Ambulance: Blodsukker for lavt",
    "Ambulance: Akut tandsmerte",
    "Ambulance: Kvinde i fødsel i bil",
    "Ambulance: Mistanke om blodprop",
    "Ambulance: Mistanke om hjerneblødning",
    "Ambulance: Akut blindtarmsbetændelse",
    "Ambulance: Galdeblærebetændelse",
    "Ambulance: Nyrestenssmerter",
    "Ambulance: Akut migrænetilfælde",
    "Ambulance: Panikangst anfald",
    "Ambulance: Hjertekramper",
    "Ambulance: Lungebetændelse",
    "Ambulance: Astmaanfald hos voksen",
    "Ambulance: Diabetisk koma",
    "Ambulance: Insulinchok",
    "Ambulance: Akut allergi reaktion",
    "Ambulance: Mad i luftvejene",
    "Ambulance: Medicin overdosis",
    "Ambulance: Kemisk forbrænding",
    "Ambulance: Elektrisk stød",
    "Ambulance: Mistanke om forgiftning",
    "Ambulance: Bevidstløshed ukendt årsag",
    "Ambulance: Akut depression med selvskade",
    // Vagt opgaver
    "Vagt: Indbrudstyveri på kontor",
    "Vagt: Brandalarmen aktiveret på hospital",
    "Vagt: Uautoriseret adgang til byggeplads",
    "Vagt: Hærværk på parkeringsplads",
    "Vagt: Mistænkelig aktivitet ved skole",
    "Vagt: Tyveriforsøg i varehus",
    "Vagt: Alkoholiseret person på privat ejendom",
    "Vagt: Overfald på parkeringsområde",
    "Vagt: Brandfare ved container",
    "Vagt: Ulovlig campering",
    "Vagt: Knust vinduer i forretning",
    "Vagt: Vanddalisme på legeplads",
    "Vagt: Indbrud i sommerhus",
    "Vagt: Mistænksom person ved boligområde",
    "Vagt: Tyveriforsøg fra bil",
    "Vagt: Ulovlig affaldsdumpning",
    "Vagt: Støjproblemer fra byggeplads",
    "Vagt: Hund løs på privat område",
    "Vagt: Graffiti på offentlig bygning",
    "Vagt: Mistænkelig pakke efterladt",
    "Vagt: Uautoriseret fest på lukket område",
    "Vagt: Skadegørelse på køretøj",
    "Vagt: Tyveriforsøg af cykler",
    "Vagt: Mistænkelig person ved børneinstitution",
    "Vagt: Ulovlig reklameskilte",
    "Vagt: Falsk alarm på sikkerhedssystem",
    "Vagt: Uautoriseret fotografering",
    "Vagt: Mistænkelig aktivitet på parkeringsplads",
    "Vagt: Tyveri fra postboks",
    "Vagt: Ulovlig hundeluftning",
    "Vagt: Skadegørelse på hegn",
    "Vagt: Mistænkelig person på tag",
    "Vagt: Ulovlig adgang til tagterrasse",
    "Vagt: Hærværk på skilte",
    "Vagt: Mistænkelig aktivitet ved ATM",
    "Vagt: Uautoriseret køretøj på privat vej",
    "Vagt: Tyveri af værktøj",
    "Vagt: Mistænkelig person ved vinduer",
    "Vagt: Ulovlig fiskeri på privat grund",
    "Vagt: Hærværk på plantekasser",
    "Vagt: Mistænkelig aktivitet i kælder",
    "Vagt: Uautoriseret brug af elevator",
    "Vagt: Tyveri fra varelager",
    "Vagt: Mistænkelig person på gårdsplads",
    "Vagt: Ulovlig opsætning af telt",
    "Vagt: Hærværk på dørhåndtag",
    "Vagt: Mistænkelig aktivitet på byggeplads om natten",
    "Vagt: Uautoriseret adgang til kælder",
    "Vagt: Tyveri af postkasser",
    "Vagt: Mistænkelig person ved indgange",
    "Vagt: Ulovlig parkering på privat grund",
    "Vagt: Hærværk på belysning",
    // Kommunale opgaver
    "Kommune: Vandledningsbrud på vej",
    "Kommune: Træ væltet over kørebane",
    "Kommune: Kloakstop i boligområde",
    "Kommune: Defekt gadebelysning",
    "Kommune: Huller i kørebanen",
    "Kommune: Fjernelse af dødt dyr",
    "Kommune: Sneoplukning af veje",
    "Kommune: Fejl på trafikly",
    "Kommune: Oversvømmelse af kælder",
    "Kommune: Defekt vejskilt",
    "Kommune: Affaldstømning nødvendigt",
    "Kommune: Bro inspektion påkrævet",
    "Kommune: Legeplads vedligeholdelse",
    "Kommune: Park rengøring efter event",
    "Kommune: Saltning af fortove",
    "Kommune: Fjernelse af grafitti",
    "Kommune: Reparation af gadelampe",
    "Kommune: Renogvandstskade",
    "Kommune: Defekt parkeringsautomat",
    "Kommune: Haveaffald indsamling",
    "Kommune: Vejarbejde koordinering",
    "Kommune: Offentligt toilet rengøring",
    "Kommune: Fjernelse af ulovlige skiltning",
    "Kommune: Vedligeholdelse af busstoppested",
    "Kommune: Inspektion af playground",
    "Kommune: Reparation af fortov",
    "Kommune: Vedligeholdelse af cykelsti",
    "Kommune: Fjernelse af sne fra gangbro",
    "Kommune: Reparation af kloakdæksel",
    "Kommune: Trimning af træer på offentlig grund",
    "Kommune: Vedligeholdelse af offentlige toiletter",
    "Kommune: Reparation af vandpost",
    "Kommune: Fjernelse af ulovlig camping",
    "Kommune: Vedligeholdelse af kirkegård",
    "Kommune: Reparation af offentlige bænke",
    "Kommune: Fjernelse af farligt affald",
    "Kommune: Inspektion af vejbump",
    "Kommune: Vedligeholdelse af fontæne",
    "Kommune: Reparation af rabat",
    "Kommune: Fjernelse af dead leaves",
    "Kommune: Vedligeholdelse af offentlige skraldespande",
    "Kommune: Reparation af busskur",
    "Kommune: Fjernelse af is fra fortove",
    "Kommune: Vedligeholdelse af offentlige havesteder",
    "Kommune: Reparation af vejafmærkning",
    "Kommune: Fjernelse af ulovlige plakater",
    "Kommune: Vedligeholdelse af offentlige p-pladser",
    "Kommune: Reparation af gadebelysning",
    "Kommune: Fjernelse af nedfaldne grene",
    "Kommune: Vedligeholdelse af skolegård",
    "Kommune: Reparation af cykelstativ",
    "Kommune: Fjernelse af slaghuller",
    "Kommune: Vedligeholdelse af offentlige blomsterbede",
    "Kommune: Reparation af vejskilte",
    "Kommune: Fjernelse af grafitti fra offentlige bygninger",
    "Kommune: Vedligeholdelse af offentlige stier",
    "Kommune: Reparation af regnvandssystem",
    "Kommune: Fjernelse af ukrudt fra fortove",
    "Kommune: Vedligeholdelse af offentlige overdækninger",
    "Kommune: Reparation af trafikspejle",
    "Kommune: Fjernelse af sne fra offentlige trapper",
    "Kommune: Vedligeholdelse af offentlige legepladser",
    "Kommune: Reparation af vejbelysning",
    // Skadeservice opgaver
    "Skadeservice: Vandskade i kælder",
    "Skadeservice: Tagskade efter storm",
    "Skadeservice: Glasskade i forretning",
    "Skadeservice: Byggeskade efter kollision",
    "Skadeservice: Røgskade efter brand",
    "Skadeservice: Rørskade i badeværelse",
    "Skadeservice: Tyveskade efter indbrud",
    "Skadeservice: Isskade på køretøj",
    "Skadeservice: Vindskade på vinduer",
    "Skadeservice: Varmeblæserskade",
    "Skadeservice: Frostskade på rørledning",
    "Skadeservice: Bygningsskade efter jordskred",
    "Skadeservice: Elmaskine skade",
    "Skadeservice: Beskadigelse af loft",
    "Skadeservice: Skade på gulvbelægning",
    "Skadeservice: Sturmskade på facade",
    "Skadeservice: Skade på inventar",
    "Skadeservice: Bilskade i garage",
    "Skadeservice: Skimmelskade efter fugt",
    "Skadeservice: Maskinkollision på arbejdsplads",
    "Skadeservice: Skade på elektronik",
    "Skadeservice: Isolering beskadiget",
    "Skadeservice: Haglskade på tag",
    "Skadeservice: Skade på varmeanlæg",
    "Skadeservice: Beskadigelse af trapper",
    // Autohjælp opgaver
    "Autohjælp: Punkteret dæk på motorvej",
    "Autohjælp: Bil starter ikke",
    "Autohjælp: Tømt for benzin",
    "Autohjælp: Batteri fladt",
    "Autohjælp: Motor overophedet",
    "Autohjælp: Nøgler låst inde i bil",
    "Autohjælp: Kørebælte knækket",
    "Autohjælp: Startmotor defekt",
    "Autohjælp: Gearkasse problem",
    "Autohjælp: Bremser fejler",
    "Autohjælp: Radiator lækage",
    "Autohjælp: Alternator defekt",
    "Autohjælp: Kobling problem",
    "Autohjælp: Tændrør defekt",
    "Autohjælp: Karburator problem",
    "Autohjælp: Olielækage",
    "Autohjælp: Kølevand lækage",
    "Autohjælp: Udstødning røg",
    "Autohjælp: Styretøj defekt",
    "Autohjælp: Hjullejring defekt",
    "Autohjælp: Drivaksel knækket",
    "Autohjælp: Vinduesviskere virker ikke",
    "Autohjælp: Aircondition defekt",
    "Autohjælp: Lygter virker ikke",
    "Autohjælp: Blinklys defekt",
    "Autohjælp: Horn virker ikke",
    "Autohjælp: Speedometer defekt",
    "Autohjælp: Brændstofpumpe defekt",
    "Autohjælp: Motorolie for lav",
    "Autohjælp: Dieselfilter tilstoppet",
    "Autohjælp: Luftfilter tilstoppet",
    "Autohjælp: Katalysator defekt",
    "Autohjælp: Lambda sonde defekt",
    "Autohjælp: Turbolader defekt",
    "Autohjælp: Kilerem knækket",
    "Autohjælp: Termometer defekt",
    "Autohjælp: Dæktryk for lavt",
    "Autohjælp: Hjul faldet af",
    "Autohjælp: Støddæmper defekt",
    "Autohjælp: Fjedre knækket",
    "Autohjælp: Håndbrems virker ikke",
    "Autohjælp: Koblingspedal virker ikke",
    "Autohjælp: Gaspedal hænger",
    "Autohjælp: Bremsepedal blød",
    "Autohjælp: Rattet låst",
    "Autohjælp: Døre kan ikke åbnes",
    "Autohjælp: Vinduer kan ikke åbnes",
    "Autohjælp: Soltag hænger",
    "Autohjælp: Kofanger løs",
    "Autohjælp: Motorhjelm kan ikke lukkes",
    "Autohjælp: Bagklap kan ikke åbnes",
    "Autohjælp: Sideruder knust",
    "Autohjælp: Forrude sprækket",
    "Autohjælp: Bagrude sprækket",
    "Autohjælp: Spejle knækket",
    "Autohjælp: Antenne knækket",
    "Autohjælp: Radio virker ikke",
    "Autohjælp: GPS navigation defekt",
    "Autohjælp: Mobiloplader virker ikke",
    "Autohjælp: Sæder kan ikke justeres",
    "Autohjælp: Sikkerhedssele hænger"
];
